FROM public.ecr.aws/lambda/python:3.10
RUN yum install -y gcc postgresql-devel && yum clean all
WORKDIR /var/task
ENV PYTHONPATH=/var/task
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY .env .
COPY src/ .
CMD ["main.handler"]