FROM public.ecr.aws/lambda/python:3.10
RUN yum install -y gcc postgresql-devel && yum clean all
WORKDIR /var/task
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY main.py .
CMD ["main.lambda_handler"]